[package]
name = "gpui-kit-backend-reqwest-client"
description = "GPUI's `reqwest_client` from whichever implementation `gpui-kit-backend` picks."
version = "0.0.0"
license = "Apache-2.0"
publish = false
edition.workspace = true

[lints]
workspace = true

[lib]
path = "lib.rs"
doctest = false

[features]
gpui-fast = ["gpui-kit-backend/gpui-fast"]

[dependencies]
gpui-kit-backend.workspace = true
